version: '3'

services:
  game_quote_bot:
    build:
      dockerfile: Dockerfile
    image: game_quote_bot_image:latest
    volumes:
      - ./src:/app/src
      - ./api_key.txt:/app/api_key.txt
      - ./quotes.json:/app/quotes.json
    expose:
      - 80
    command: ["python", "src/app.py", "api_key.txt", "quotes.json"]
    labels:
      - traefik.enable=true
      - "traefik.http.routers.game_quote_bot.rule=Host(`ltgmc.online`) && PathPrefix(`/bot`)"
      - "traefik.http.routers.game_quote_bot.tls=true"
      - "traefik.http.routers.game_quote_bot.tls.certResolver=lets-encrypt-ssl"
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring_monitoring
    external: true
